### ISSUE TITLE
Differences pc and ios versions

### ISSUE THREAD

**Issue by ghost** [reddragon/eclisp-iOS#11]
I noticed something in this code:
    (defun mod(a b)(cond((< a b)a)(true(mod(- a b)b))))
On the PC call function is working
    (mod 16 32)
    16
And on iOS:
    > (mod 16 32)
    Undefined variable: a

**Comment by reddragon** [comment]
This could be because the app ships with a pre-compiled library. I haven't updated the app in a while. Plan to do that along with bigint support.

**Comment by reddragon** [comment]
Thanks for reporting this, though.

**Comment by reddragon** [comment]
I've updated the app a few days back. You should be able to see similar results on both, the app & with the latest command-line based REPL.
